import { MigrationInterface, QueryRunner } from "typeorm";

export class ALTERACTIVITY1732035407005 implements MigrationInterface {
    name = 'ALTERACTIVITY1732035407005'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`FK_856efdd136dff1362f39e292a5d\` ON \`demandeProlongation\``);
        await queryRunner.query(`DROP INDEX \`FK_0b60e6cf85e054f08ab9c019a78\` ON \`sousActivity\``);
        await queryRunner.query(`DROP INDEX \`FK_3571467bcbe021f66e2bdce96ea\` ON \`activity\``);
        await queryRunner.query(`DROP INDEX \`FK_85fe1974be2cafc824f151bf288\` ON \`user\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`dateFinReel\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`resultatObtenu\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`budgetConsomme\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`resultat\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`resultatObtenu\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`province\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`responsable\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`budget\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`budgetConsomme\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`livrable\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`dateFinReel\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`etat\` varchar(255) NULL DEFAULT 'En attente'`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`impact\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`impact\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`niveau\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`niveau\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`reponse\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`reponse\` varchar(255) NOT NULL DEFAULT 'En attente'`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`commentaire\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`commentaire\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`titre\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`titre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`resultat\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`resultat\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`province\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`province\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`responsable\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`responsable\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`autreService\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`autreService\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`debut\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`debut\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`fin\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`fin\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`indicateur\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`indicateur\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`budget\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`budget\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`livrable\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`livrable\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` CHANGE \`activityId\` \`activityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`titre\``);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`titre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`status\` varchar(255) NULL DEFAULT 'En attente'`);

        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD CONSTRAINT \`FK_856efdd136dff1362f39e292a5d\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD CONSTRAINT \`FK_60bc4dbcd1770ec0a6b689640a1\` FOREIGN KEY (\`activityId\`) REFERENCES \`activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD CONSTRAINT \`FK_0b60e6cf85e054f08ab9c019a78\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD CONSTRAINT \`FK_38e5f6d4a785ff0ec835c6fb943\` FOREIGN KEY (\`activityId\`) REFERENCES \`activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_3571467bcbe021f66e2bdce96ea\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
      
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_f31746ae11a090306b0b2670b00\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_85fe1974be2cafc824f151bf288\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_3571467bcbe021f66e2bdce96ea\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP FOREIGN KEY \`FK_38e5f6d4a785ff0ec835c6fb943\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP FOREIGN KEY \`FK_0b60e6cf85e054f08ab9c019a78\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP FOREIGN KEY \`FK_60bc4dbcd1770ec0a6b689640a1\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP FOREIGN KEY \`FK_856efdd136dff1362f39e292a5d\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`grade\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`grade\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`fonction\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`fonction\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`direction\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`direction\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`username\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`username\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`telephone\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`telephone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`prenom\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`prenom\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`postnom\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`postnom\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`nom\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`nom\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`status\` varchar(255) NULL DEFAULT 'En attente'`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`titre\``);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`titre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` CHANGE \`activityId\` \`activityId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`livrable\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`livrable\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`budget\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`budget\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`indicateur\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`indicateur\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`fin\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`fin\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`debut\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`debut\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`autreService\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`autreService\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`responsable\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`responsable\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`province\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`province\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`resultat\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`resultat\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`titre\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD \`titre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`commentaire\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`commentaire\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`reponse\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`reponse\` varchar(255) NOT NULL DEFAULT 'En attente'`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`niveau\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`niveau\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`impact\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`impact\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`etat\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`dateFinReel\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`livrable\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`budgetConsomme\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`budget\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`responsable\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`province\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`resultatObtenu\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`resultat\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`budgetConsomme\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`resultatObtenu\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP COLUMN \`dateFinReel\``);
        await queryRunner.query(`CREATE INDEX \`FK_85fe1974be2cafc824f151bf288\` ON \`user\` (\`directeurId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_3571467bcbe021f66e2bdce96ea\` ON \`activity\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_0b60e6cf85e054f08ab9c019a78\` ON \`sousActivity\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_856efdd136dff1362f39e292a5d\` ON \`demandeProlongation\` (\`userId\`)`);
    }

}
