import { MigrationInterface, QueryRunner } from "typeorm";

export class ADDENTITIES1776941379518 implements MigrationInterface {
    name = 'ADDENTITIES1776941379518'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`annotationActivity\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`type\` varchar(255) NULL DEFAULT 'COMMENTAIRE', \`text\` text NOT NULL, \`activityId\` int NOT NULL, \`userId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`demande-user\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`demandeId\` int NOT NULL, \`date_validation\` datetime NULL, \`comment\` text NULL, \`isValidate\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`demandeProlongation\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`description\` text NOT NULL, \`impact\` varchar(255) NOT NULL, \`niveau\` varchar(255) NOT NULL, \`reponse\` varchar(255) NOT NULL DEFAULT 'En attente', \`commentaire\` text NOT NULL, \`activityId\` int NOT NULL, \`userId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user-livrable\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`livrableId\` int NOT NULL, \`date_validation\` datetime NULL, \`comment\` text NULL, \`isValidate\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`livrable\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`livrable\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`status\` varchar(255) NULL DEFAULT 'En attente', \`responsable\` varchar(255) NULL, \`dateLivraisonAttendue\` varchar(255) NULL, \`dateLivraisonReelle\` varchar(255) NULL, \`typelivrable\` varchar(255) NULL, \`livrablefileName\` varchar(255) NULL, \`support\` varchar(255) NULL, \`dateValidationAttendue\` varchar(255) NULL, \`dateValidationReel\` varchar(255) NULL, \`commentaire\` varchar(255) NULL, \`livrableQuality\` int(3) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`activity\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`titre\` text NOT NULL, \`description\` varchar(255) NULL, \`resultat\` varchar(255) NOT NULL, \`resultatObtenu\` varchar(255) NULL, \`province\` varchar(255) NOT NULL, \`direction\` varchar(255) NULL, \`responsable\` varchar(255) NULL, \`budget\` int NULL DEFAULT '0', \`budgetConsomme\` int NULL, \`dateDebut\` date NULL, \`dateFin\` date NULL, \`dateFinReel\` date NULL, \`status\` varchar(255) NULL DEFAULT 'En attente', \`etat\` varchar(255) NULL, \`priorite\` varchar(255) NULL DEFAULT 'En attente', \`deadlineRate\` int(3) NULL, \`nbre_ressource\` int(3) NULL, \`userId\` int NULL, \`livrableId\` int NULL, UNIQUE INDEX \`REL_c3dd9f7a5f6f90c5d1b3087fb4\` (\`livrableId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`auditLog\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`tableName\` varchar(255) NULL, \`entityId\` int NULL, \`action\` varchar(255) NULL, \`oldData\` json NULL, \`newData\` json NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_activies_assignment\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`sousActivityId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`nom\` varchar(255) NOT NULL, \`postnom\` varchar(255) NULL, \`prenom\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`sexe\` varchar(255) NOT NULL, \`telephone\` varchar(255) NULL, \`otp\` varchar(255) NULL, \`username\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL DEFAULT 'N/A', \`isSupervisor\` tinyint NOT NULL DEFAULT 0, \`isActive\` tinyint NOT NULL DEFAULT 0, \`status\` tinyint NOT NULL DEFAULT 1, \`directionId\` int NULL, \`directionGeneraleId\` int NULL, \`serviceId\` int NULL, \`divisionId\` int NULL, \`division\` varchar(255) NULL, \`isSetPassword\` tinyint NOT NULL DEFAULT 0, \`service\` varchar(255) NULL, \`direction\` varchar(255) NULL, \`fonction\` varchar(255) NULL, \`grade\` varchar(255) NULL, \`directeurId\` int NULL, \`agentDelegueId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_sous_activity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`message\` text NOT NULL, \`resources\` json NULL, \`isProgressUpdate\` tinyint NOT NULL DEFAULT 0, \`userId\` int NOT NULL, \`sousActivityId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sousActivity\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`titre\` text NOT NULL, \`resultat\` text NOT NULL, \`province\` varchar(255) NOT NULL, \`responsable\` varchar(255) NOT NULL, \`autreService\` varchar(255) NULL, \`debut\` varchar(255) NULL, \`fin\` varchar(255) NULL, \`dateFinReel\` date NULL, \`indicateur\` text NULL, \`resultatObtenu\` text NULL, \`status\` varchar(255) NULL DEFAULT 'En attente', \`budget\` int NULL DEFAULT '0', \`budgetConsomme\` int NULL, \`activityId\` int NULL, \`userId\` int NULL, \`livrableId\` int NULL, \`deadlineRate\` int(3) NULL, \`nbre_ressource\` int(3) NULL, \`observations\` text NULL, UNIQUE INDEX \`REL_19938e31a1e6e78edfa60d5288\` (\`livrableId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`project_copir\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`direction\` enum ('Direction des Coordinations', 'Direction Financière', 'Direction des Opérations', 'Direction des Finances', 'Autres') NOT NULL, \`status\` enum ('Planifié', 'En cours', 'Terminé', 'En retard') NOT NULL DEFAULT 'Planifié', \`progress\` int NOT NULL DEFAULT '0', \`dueDate\` date NULL, \`completionDate\` date NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`presence\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`date\` date NOT NULL, \`checkInTime\` datetime NULL, \`checkOutTime\` datetime NULL, \`checkInLatitude\` decimal(10,8) NULL, \`checkInLongitude\` decimal(11,8) NULL, \`checkOutLatitude\` decimal(10,8) NULL, \`checkOutLongitude\` decimal(11,8) NULL, \`status\` enum ('Présent', 'Absent', 'En retard', 'Demi-journée') NOT NULL DEFAULT 'Présent', \`isLate\` tinyint NOT NULL DEFAULT 0, \`delayMinutes\` int NOT NULL DEFAULT '0', \`deviceInfo\` varchar(255) NULL, \`commentaire\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`antenne\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`nom\` varchar(255) NOT NULL, \`code\` varchar(255) NULL, \`adresse\` varchar(255) NULL, \`responsable\` varchar(255) NULL, \`status\` enum ('Active', 'Inactive/Suspendue') NOT NULL DEFAULT 'Active', \`coordinationId\` int NOT NULL, \`nombreAgents\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coordination\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`nom\` varchar(255) NOT NULL, \`type\` enum ('Recouvrement', 'Administrative') NOT NULL DEFAULT 'Administrative', \`province\` varchar(255) NOT NULL, \`adresse\` varchar(255) NULL, \`status\` enum ('Active', 'En cours de mise en place') NOT NULL DEFAULT 'Active', \`coordonnateurNom\` varchar(255) NULL, \`coordonnateurTelephone\` varchar(255) NULL, \`coordonnateurEmail\` varchar(255) NULL, \`effectifActuel\` int NOT NULL DEFAULT '0', \`effectifPrevu\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`charroi\` (\`id\` int NOT NULL AUTO_INCREMENT, \`marque\` varchar(255) NOT NULL, \`modele\` varchar(255) NOT NULL, \`immatriculation\` varchar(255) NOT NULL, \`status\` enum ('Opérationnel', 'En panne', 'Maintenance', 'Non affecté') NOT NULL DEFAULT 'Opérationnel', \`coordinationId\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d01a8fe3d1e75531463cab78b6\` (\`immatriculation\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`tresorerie_mouvement\` DROP COLUMN \`motif\``);
        await queryRunner.query(`ALTER TABLE \`tresorerie_mouvement\` ADD \`motif\` varchar(255) NOT NULL COMMENT 'Motif ou libellé du mouvement (ex: Frais de communication)'`);
        await queryRunner.query(`ALTER TABLE \`annotationActivity\` ADD CONSTRAINT \`FK_c21c8b2f96df2aaa95bc9b3e852\` FOREIGN KEY (\`activityId\`) REFERENCES \`activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`annotationActivity\` ADD CONSTRAINT \`FK_79050c9930c98928590df36b1bc\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`demande-user\` ADD CONSTRAINT \`FK_80ae216f4dfda7bff6674374bd6\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`demande-user\` ADD CONSTRAINT \`FK_d411ca74f66a0e0012597c196de\` FOREIGN KEY (\`demandeId\`) REFERENCES \`demandeProlongation\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD CONSTRAINT \`FK_856efdd136dff1362f39e292a5d\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` ADD CONSTRAINT \`FK_60bc4dbcd1770ec0a6b689640a1\` FOREIGN KEY (\`activityId\`) REFERENCES \`activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user-livrable\` ADD CONSTRAINT \`FK_d441346a0c52533284ea4dc9c4f\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user-livrable\` ADD CONSTRAINT \`FK_e9ce17b02719b8b282200c80ebc\` FOREIGN KEY (\`livrableId\`) REFERENCES \`livrable\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_3571467bcbe021f66e2bdce96ea\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_c3dd9f7a5f6f90c5d1b3087fb49\` FOREIGN KEY (\`livrableId\`) REFERENCES \`livrable\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`auditLog\` ADD CONSTRAINT \`FK_3db0f7e715a0e3516bdf2e52877\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_activies_assignment\` ADD CONSTRAINT \`FK_cd9c1ea2613cd2b764a5c7b16ff\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_activies_assignment\` ADD CONSTRAINT \`FK_bffea4bf04cf6a53bfbeeed9548\` FOREIGN KEY (\`sousActivityId\`) REFERENCES \`sousActivity\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_sous_activity\` ADD CONSTRAINT \`FK_c9b926f6fb728145cd87dfa103b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_sous_activity\` ADD CONSTRAINT \`FK_7cc4f31ae48e9427115058b549a\` FOREIGN KEY (\`sousActivityId\`) REFERENCES \`sousActivity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD CONSTRAINT \`FK_0b60e6cf85e054f08ab9c019a78\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD CONSTRAINT \`FK_38e5f6d4a785ff0ec835c6fb943\` FOREIGN KEY (\`activityId\`) REFERENCES \`activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` ADD CONSTRAINT \`FK_19938e31a1e6e78edfa60d52881\` FOREIGN KEY (\`livrableId\`) REFERENCES \`livrable\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`presence\` ADD CONSTRAINT \`FK_6c0fa00ffa14c9eaf62cc32a600\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`antenne\` ADD CONSTRAINT \`FK_69e666f90eaa3ce3903c80abfa9\` FOREIGN KEY (\`coordinationId\`) REFERENCES \`coordination\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`charroi\` ADD CONSTRAINT \`FK_c15e48cef0b736293f9f0effac1\` FOREIGN KEY (\`coordinationId\`) REFERENCES \`coordination\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`charroi\` DROP FOREIGN KEY \`FK_c15e48cef0b736293f9f0effac1\``);
        await queryRunner.query(`ALTER TABLE \`antenne\` DROP FOREIGN KEY \`FK_69e666f90eaa3ce3903c80abfa9\``);
        await queryRunner.query(`ALTER TABLE \`presence\` DROP FOREIGN KEY \`FK_6c0fa00ffa14c9eaf62cc32a600\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP FOREIGN KEY \`FK_19938e31a1e6e78edfa60d52881\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP FOREIGN KEY \`FK_38e5f6d4a785ff0ec835c6fb943\``);
        await queryRunner.query(`ALTER TABLE \`sousActivity\` DROP FOREIGN KEY \`FK_0b60e6cf85e054f08ab9c019a78\``);
        await queryRunner.query(`ALTER TABLE \`chat_sous_activity\` DROP FOREIGN KEY \`FK_7cc4f31ae48e9427115058b549a\``);
        await queryRunner.query(`ALTER TABLE \`chat_sous_activity\` DROP FOREIGN KEY \`FK_c9b926f6fb728145cd87dfa103b\``);
        await queryRunner.query(`ALTER TABLE \`user_activies_assignment\` DROP FOREIGN KEY \`FK_bffea4bf04cf6a53bfbeeed9548\``);
        await queryRunner.query(`ALTER TABLE \`user_activies_assignment\` DROP FOREIGN KEY \`FK_cd9c1ea2613cd2b764a5c7b16ff\``);
        await queryRunner.query(`ALTER TABLE \`auditLog\` DROP FOREIGN KEY \`FK_3db0f7e715a0e3516bdf2e52877\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_c3dd9f7a5f6f90c5d1b3087fb49\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_3571467bcbe021f66e2bdce96ea\``);
        await queryRunner.query(`ALTER TABLE \`user-livrable\` DROP FOREIGN KEY \`FK_e9ce17b02719b8b282200c80ebc\``);
        await queryRunner.query(`ALTER TABLE \`user-livrable\` DROP FOREIGN KEY \`FK_d441346a0c52533284ea4dc9c4f\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP FOREIGN KEY \`FK_60bc4dbcd1770ec0a6b689640a1\``);
        await queryRunner.query(`ALTER TABLE \`demandeProlongation\` DROP FOREIGN KEY \`FK_856efdd136dff1362f39e292a5d\``);
        await queryRunner.query(`ALTER TABLE \`demande-user\` DROP FOREIGN KEY \`FK_d411ca74f66a0e0012597c196de\``);
        await queryRunner.query(`ALTER TABLE \`demande-user\` DROP FOREIGN KEY \`FK_80ae216f4dfda7bff6674374bd6\``);
        await queryRunner.query(`ALTER TABLE \`annotationActivity\` DROP FOREIGN KEY \`FK_79050c9930c98928590df36b1bc\``);
        await queryRunner.query(`ALTER TABLE \`annotationActivity\` DROP FOREIGN KEY \`FK_c21c8b2f96df2aaa95bc9b3e852\``);
        await queryRunner.query(`ALTER TABLE \`tresorerie_mouvement\` DROP COLUMN \`motif\``);
        await queryRunner.query(`ALTER TABLE \`tresorerie_mouvement\` ADD \`motif\` varchar(255) NOT NULL COMMENT 'Motif ou libellé du mouvement (ex: Frais de communication)'`);
        await queryRunner.query(`DROP INDEX \`IDX_d01a8fe3d1e75531463cab78b6\` ON \`charroi\``);
        await queryRunner.query(`DROP TABLE \`charroi\``);
        await queryRunner.query(`DROP TABLE \`coordination\``);
        await queryRunner.query(`DROP TABLE \`antenne\``);
        await queryRunner.query(`DROP TABLE \`presence\``);
        await queryRunner.query(`DROP TABLE \`project_copir\``);
        await queryRunner.query(`DROP INDEX \`REL_19938e31a1e6e78edfa60d5288\` ON \`sousActivity\``);
        await queryRunner.query(`DROP TABLE \`sousActivity\``);
        await queryRunner.query(`DROP TABLE \`chat_sous_activity\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`user_activies_assignment\``);
        await queryRunner.query(`DROP TABLE \`auditLog\``);
        await queryRunner.query(`DROP INDEX \`REL_c3dd9f7a5f6f90c5d1b3087fb4\` ON \`activity\``);
        await queryRunner.query(`DROP TABLE \`activity\``);
        await queryRunner.query(`DROP TABLE \`livrable\``);
        await queryRunner.query(`DROP TABLE \`user-livrable\``);
        await queryRunner.query(`DROP TABLE \`demandeProlongation\``);
        await queryRunner.query(`DROP TABLE \`demande-user\``);
        await queryRunner.query(`DROP TABLE \`annotationActivity\``);
    }

}
